name: qs_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: 0.10.1
  flutter_screenutil: 5.8.4
  flutter_bloc: 8.1.3
  equatable: 2.0.5
  get_it: 7.6.0
  dio: 4.0.6
  pretty_dio_logger: 1.2.0-beta-1
  logger: 1.1.0
  shared_preferences: 2.2.0
  flutter_svg: 2.0.7
  intl: ^0.18.0
  go_router: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dart_code_metrics: any
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
#    - .env
    - lib/features/landing/presentation/assets/image/

